---
- name: Instalar apache2
  apt: name=apache2 state=latest
- name: Iniciar y habilitar servicio
  service: name=apache2 state=started enabled=true
- name: Copiar fichero de configuración
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf

- name: Copiar fichero index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

