---
#ansible when
#ansible and
- name: instalar nginx
  hosts: 192.168.20.171
  become: yes #Ejecuta como root
  tasks:
    - name: Instalar paquetes
      yum:
        name:
          - httpd
          - mariadb-server
          - php
        state: present
      when: ansible_distribution == 'CentOS' and ansible_kernel == '2.10' #este es el when que valida que se instale sobre la distribución correcta