---
- name: Instala apache y activa servicio
  hosts: test


  tasks:
  - name: Instala apache
    yum:
      name: httpd
      state: present


  - name: activa servicio apache
    service:
      name: httpd
      state: started
   
