---
#Este playbook se ejecuta con (cambiar la contraseña de pepe):
#ansible-playbook cambia_pwd.yaml --extra-vars newpassword=pepe123
#Se puede usar -kk al final para preguntar pwd
#Nota: Se debe tener instalado pip y con pip instaldo passlib
#pip install passlib
- hosts: test
  become: true
   tasks:
  
  - name: instala lista paquetes nginx
    ansible.builtin.yum:
      name:
        - nginx
        - postgresql
        - postgresql-server
      state: present

