---

#Indica ejecución de tareas en todos los servidores
- hosts: homeservers 
  tasks: 
  - name: vim install
    apt: name=cowsay state=present
    become: true
  - name: saluda
    shell: cowsay "hola"
